### ISSUE TITLE
Expose optimizers, OptimizationProblem and Observation

### ISSUE THREAD

**Issue by miquelmarti** [Dreem-Organization/benderopt#1]
Hi, 

Thank you so much for this package! Was looking for a hyperparameter optimizer that was both simple and easy to integrate and this just hit the nail on the head.

However, I have to access the underlying classes and methods to fit my use case via a small hack:
```
import benderopt.minimize as benderopt

benderopt.OptimizationProblem...
```

I suggest to allow more flexibility by adding these to `__init__.py` instead. The `minimize` point of access does not work for me, I imagine many people would like a slightly lower level access too.

If the decision is not to go in this direction I hope you keep the backdoor open :stuck_out_tongue:

**Comment by vthorey** [comment]
Hi,

Thanks a lot for your feedback, it means a lot!

I am not sure I fully understood your use case, to access base classes you could do

`from benderopt.base import OptimizationProblem`

or 

```
import benderopt

benderopt.base.OptimizationProblem
```

**Comment by miquelmarti** [comment]
Thank you for your answer. It's just that. I could not do it yesterday when I cloned the repo that's why I was trying to do this weird thing... I guess I messed things up somehow but after importing `benderopt.base` did not exist, only `benderopt.minimize`.

Anyway, it works the way you say installing from pip. Thanks!
