### ISSUE TITLE
Initial guess

### ISSUE THREAD

**Issue by c0d3rman** [Dreem-Organization/benderopt#2]
Hi, is there a way to provide an initial guess or starting point for the exploration? Should I just build a custom OptimizationProblem object with an observation already filled in? I tried doing this like the example using `OptimizationProblem.from_json`, but it seems that it won't take a dictionary, only strings or other objects.

**Comment by vthorey** [comment]
Hi, You can use 

```
optimization_problem = OptimizationProblem.from_list([
    {
        "name": "param1",
        "category": "category",
        "search_space": {"values": ["a", "b"]}
    },
    {
        "name": "param1",
        "category": "normal",
        "search_space": {"values": [1, 2]}
    }
])

optimization_problem.add_observations_from_list(
    [
        {
            "loss": 0.5,
            "parameters": {"param1": "a", "param2": 1.5}
        },
        {
            "loss": 0.7,
            "parameters": {"param1": "a", "param2": 1.8}
        },
        {
            "loss": 0.1,
            "parameters": {"param1": "b", "param2": 1.1}
        },
]
```

**Comment by c0d3rman** [comment]
Ah, I think I see my issue. I was trying to use `minimize`, but it seems like that function only accepts a list, and throws an error (UnboundLocalError: local variable 'optimization_problem' referenced before assignment) if it's passed in anything else. If I implement `minimize` myself it works fine. All it takes is copying the code from `minimize` and replacing all occurrences of `optimization_problem_parameters` with `optimization_problem`. It seems like this was the original intention for `minimize`?

**Comment by vthorey** [comment]
You are right, It is clarified now thanks!
