### ISSUE TITLE
ValidationError Message

### ISSUE THREAD

**Issue by JoLo90** [Dreem-Organization/benderopt#3]
Hi, first of all thank you for this excellent optimization package.

When setting wrong settings for an uniform parameter:

`   {
        "name": "WestWWR", 
        "category": "uniform",
        "search_space": {
            "low": 0.0,
            "high": 0.15,
            "step": 0.20}
    },`

I get `ValidationError: 'step' must be strictly superior than 'high'`

Shouldn't it be the other way around  ?
'**high**' must be strictly superior than '**step**'

**Comment by vthorey** [comment]
Hello,

Thanks for the kind words. You are right it should be the over way around. Or **superior** should be **inferior**.
